services:
  # PostgreSQL Database
  - type: pserv
    name: habicore-pos-db
    env: node
    plan: free
    region: oregon
    
  # Backend API Service
  - type: web
    name: habicore-pos-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install && npx prisma generate && npm run build
    startCommand: cd backend && npx prisma migrate deploy && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: DATABASE_URL
        fromDatabase:
          name: habicore-pos-db
          property: connectionString
      - key: CORS_ORIGIN
        fromService:
          type: web
          name: habicore-pos-frontend
          property: host
    healthCheckPath: /health
    
  # Frontend React App
  - type: web
    name: habicore-pos-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: habicore-pos-backend
          property: host
      - key: NODE_ENV
        value: production
